### ISSUE TITLE
Error Lime Method

### ISSUE THREAD

**Issue by naturallyfunny** [teamalgoritma/community#754]
### Chunk:
```
explainer <- lime(x = X_train, model = model_dt)

explanation <- explain(x = X_test %>% slice(1:4),
                       labels = "insufficient",
                       explainer = explainer,
                       n_features = 3)


plot_features(explanation)
```

### Error:
```
explanation <- explain(x = X_test %>% slice(1:4),
                       labels = "insufficient",
                       explainer = explainer,
                       n_features = 3)
```
Error in explain(x = X_test %>% slice(1:4), labels = "insufficient", explainer = explainer, :
argument "model" is missing, with no default

### model = model_dt:
```
# assign parameter model:
explanation <- explain(x = X_test %>% slice(1:4),
                       labels = "insufficient",
                       explainer = explainer,
                       n_features = 3,
                       model = model_dt)
```

###  Error setelah assign parameter model:
`plot_features(explanation)`
Error in explain(x = X_test %>% slice(1:4), labels = "insufficient", explainer = explainer, :
argument "model" is missing, with no default

_Originally posted by @ArdiantheGreat in https://github.com/teamalgoritma/community/discussions/753#discussioncomment-6845863_

**Comment by Yusraf002** [comment]
Dear @ArdiantheGreat 

Kami ingin memberitahukan bahwa masalah yang terkait dengan error telah berhasil diselesaikan melalui diskusi. Kami ingin menginformasikan bahwa kami akan menutup issue ini. Terima kasih atas kerja sama dan partisipasinya.

Best Regards,
Team Algoritma
