### ISSUE TITLE
Xion EDA : Cara EDA yang mendalam

### ISSUE THREAD

**Issue by ammaralwandi97** [teamalgoritma/community#815]
, minta tolong dijelaskan pentingnya dan bagaimana cara melakukan EDA yang kompleks sehingga data benar-benar siap diolah. karena 80% analisis data adalah pre-processing.

**Comment by Yusraf002** [comment]
Dear @ammaralwandi97 

Mohon maaf atas keterlambatan dalam menanggapi isu ini. Penting untuk dicatat bahwa EDA (Exploratory Data Analysis) memiliki peran krusial sebagai landasan sebelum memulai analisis. karena pada tahapan EDA kita akan memperoleh informasi-informasi penting dari data yang kita miliki dan nantinya dapat digunakan dalam menjawab pertanyaan bisnis atau menjadi ide pemecahan masalah menggunakan machine learning. Kompleksitas EDA bergantung pada data dan kasus yang dihadapi, namun beberapa langkah berikut dapat dijadikan sebagai acuan dasar:

1. Lakukan analisis deskriptif, meliputi nilai terpusat, sebaran data, korelasi, dan pengujian statistik sederhana.
2. Agregasi data sederhana untuk menjawab pertanyaan bisnis yang ada.
3. Gunakan visualisasi sederhana untuk mendapatkan insight dari data.
4. Terapkan visualisasi tingkat lanjut untuk presentasi hasil analisis.

Semoga jawaban ini dapat membantu, dan untuk pertanyaan selanjutnya silakan ajukan di bagian diskusi. 
Terima kasih atas pemahaman dan kerjasamanya.



Best Regards.
Team Algoritma.
