### ISSUE TITLE
Sudah import pandas tapi masih error

### ISSUE THREAD

**Issue by imronovsky2000** [teamalgoritma/community#875]
Sudah import pandas dan berhasil kenapa masih error ya?
source datanya juga sudah ada ( rice.csv)
'rice = pd.read_csv('data_input/rice.csv')'
'rice'
error : 
NameError                                 Traceback (most recent call last)
Cell In[16], [line 1](vscode-notebook-cell:?execution_count=16&line=1)
----> [1](vscode-notebook-cell:?execution_count=16&line=1) rice = pd.read_csv('data_input/rice.csv')
      [2](vscode-notebook-cell:?execution_count=16&line=2) rice

NameError: name 'pd' is not defined

**Comment by ramdhinafinita** [comment]
Dear @imronovsky2000 

Error diatas menyebutkan kalau pd belum terdefinisi, bisa dicek kembali apakah import pandas yang sudah dibuat tersebut sudah dijalankan?

![image](https://github.com/teamalgoritma/community/assets/64061969/cbcd564c-47f7-4d24-8589-fb4e7eb90b3e)

Jika sudah dijalankan, seharusnya tampilan akan sama seperti yang ada diatas. Terimaaksih semoga membantu..

**Comment by imronovsky2000** [comment]
rupanya kurang ' as pd ' dalam command saya , kenapa tidak memunculkan error ya
